%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MATLAB Code Generated with Fuzzy Logic Designer App                     %
%                                                                         %
% Date: 04-Dec-2025 21:05:31                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc; clear; close all;

% Construct FIS
DroneAltitudeController = mamfis(Name="DroneAltitudeController");
% Input 1
DroneAltitudeController = addInput(DroneAltitudeController,[-2 2],Name="error");
DroneAltitudeController = addMF(DroneAltitudeController,"error","trimf",[-2 -1 0], ...
    Name="Negative",VariableType="input");
DroneAltitudeController = addMF(DroneAltitudeController,"error","trimf",[-0.5 0 0.5], ...
    Name="Zero",VariableType="input");
DroneAltitudeController = addMF(DroneAltitudeController,"error","trimf",[0 1 2], ...
    Name="Positive",VariableType="input");
% Input 2
DroneAltitudeController = addInput(DroneAltitudeController,[-2 2],Name="derror");
DroneAltitudeController = addMF(DroneAltitudeController,"derror","trimf",[-2 -1 0], ...
    Name="Down",VariableType="input");
DroneAltitudeController = addMF(DroneAltitudeController,"derror","trimf",[-0.5 0 0.5], ...
    Name="Stable",VariableType="input");
DroneAltitudeController = addMF(DroneAltitudeController,"derror","trimf",[0 1 2], ...
    Name="Up",VariableType="input");
% Output 1
DroneAltitudeController = addOutput(DroneAltitudeController,[0 100],Name="thrust");
DroneAltitudeController = addMF(DroneAltitudeController,"thrust","trimf",[0 25 50], ...
    Name="Low",VariableType="output");
DroneAltitudeController = addMF(DroneAltitudeController,"thrust","trimf",[30 50 70], ...
    Name="Medium",VariableType="output");
DroneAltitudeController = addMF(DroneAltitudeController,"thrust","trimf",[50 75 100], ...
    Name="High",VariableType="output");
% Rules
DroneAltitudeController = addRule(DroneAltitudeController,[1 1 1 1 1; ...
    1 2 1 1 1; ...
    1 3 2 1 1; ...
    2 1 2 1 1; ...
    2 2 1 1 1; ...
    2 3 3 1 1; ...
    3 1 2 1 1; ...
    3 2 3 1 1; ...
    3 3 3 1 1]);